### ISSUE TITLE
GLES2 compatibility

### ISSUE THREAD

**Issue by sasmaster** [jdduke/three_cpp#7]
Hi there! Do you plan to continue developing this lib?I could give a hand ,though my JS sucks.But I would like to make it GLES2 compatible to be compiled on Emscripten as well.

**Comment by futagoza** [comment]
Hi Michael,
You might want to to watch another fork: https://github.com/elwinarens/three_cpp
Elwin is updating his constantly and has began adding stuff from the r60+ release's of Three.js

**Comment by sasmaster** [comment]
Btw,just tried to compile on VS2012 and there are errors in several files.Like in memory.hpp.

**Comment by jdduke** [comment]
futagoza's suggestion, tracking https://github.com/elwinarens/three_cpp, is your best bet if you want recent updates.  I have every intention of merging the elwinarens branch upstream, though I do not have a timeline for making good on that.

As for compile errors, please file an issue with the appropriate details; "there are errors" doesn't give me much to go on. VS2012 support will likely be deprecated in favor of VS2013 at some point.

**Comment by sasmaster** [comment]
Well,I am getting errors for "toArray()"  .I think it has something to do
with variadic templates which are kind of not supported well in 2012....I
also checked the fork of the guy you recommended and got the same errors.

On Mon, Apr 7, 2014 at 12:32 AM, Jared Duke notifications@github.comwrote:

> futagoza's suggestion, tracking https://github.com/elwinarens/three_cpp,
> is your best bet if you want recent updates. I have every intention of
> merging the elwinarens branch upstream, though I do not have a timeline for
> making good on that.
> 
> As for compile errors, please file an issue with the appropriate details;
> "there are errors" doesn't give me much to go on. VS2012 support will
> likely be deprecated in favor of VS2013 at some point.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/jdduke/three_cpp/issues/7#issuecomment-39682491
> .

## 

Michael Ivanov
Graphics Software
onlygraphix.com
Tel:+972 54 4962254

**Comment by jdduke** [comment]
Have you tried with the Nov 2012 CTP update? http://www.microsoft.com/en-us/download/details.aspx?id=35515

**Comment by ghost** [comment]
We're currently working on updating the port to three.js's tag r65. My branch has just been merged and moved to this repository in the dev_r65 branch. The r65 branch does build, but the port is currently unfinished/unstable. I'm hoping the update of the core library is finished either this month or the next.  After that we can look into adding features. 

There's a Trello board i've been using to keep track of progress, which can be found here https://trello.com/b/dFiY7MOE/three-cpp.

About the build errors: the master branch should build with MCVS 2012 Update 4.

**Comment by sasmaster** [comment]
Well,I installed that update and seems the language related errors are gone.Now I am getting SDL errors (as  I don't use SDL)...I also see you init GL context with GLEW internally.I think it is a bad practice forcing users using specific lib .Is SDL also used somewhere internally by the API ?

**Comment by sasmaster** [comment]
Also I am getting tons of "unresolved external symbol" for three objects even though I just included the headers.

**Comment by jdduke** [comment]
Yes, it is bad practice to force users into such a dependency.  There are lots of bad practices in the code, and I would warn anybody about using this in any kind of production software.  That said, I do have plans to eliminate the explicit sdl/glew dependency from the core library, allowing the embedder to provide the gl context.

As for compilation issues on the dev branch, the project will no longer support header-only builds.  It was a novelty that I played with initially, and in hindsight it was probably a mistake given the nature of the project.

**Comment by sasmaster** [comment]
So I need to compile it ?

On Sat, Apr 19, 2014 at 5:55 PM, Jared Duke notifications@github.comwrote:

> Yes, it is bad practice to force users into such a dependency. There are
> lots of bad practices in the code, and I would warn anybody about using
> this in any kind of production software. That said, I do have plans to
> eliminate the explicit sdl/glew dependency from the core library, allowing
> the embedder to provide the gl context.
> 
> As for compilation issues on the dev branch, the project will no longer
> support header-only builds. It was a novelty that I played with initially,
> and in hindsight it was probably a mistake given the nature of the project.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jdduke/three_cpp/issues/7#issuecomment-40871499
> .

## 

Michael Ivanov
Graphics Software
onlygraphix.com
Tel:+972 54 4962254

**Comment by jdduke** [comment]
Yes, you will need to compile it.  However, as a dev branch, it's in an _extremely_ unstable state, so again, please don't rely on it for active development.

I've got a work-in-progress version that removes the GLEW dependency entirely, as well as GL linkage dependencies from the core three library.  This includes a switch to SDL2, and it should support GLES as well.  My goal is to include this as part of the r65 release, whenever that may be...

**Comment by jdduke** [comment]
Just a heads up, the dev_r65 branch (still not fully functional) now compiles without any explicit GL library dependencies, using an embedder provided GL context.  It also compiles just fine with GLES2 for Android (thought that's still untested end-to-end).

I've also upgraded the SDL version used by the examples to SDL 2.0.3, and removed the GLEW dependency entirely.
